-- Checks nvim config repo status & notifies when behind
--
-- This code is generated by Google Gemini

local function check_config_updates()
	local config_path = vim.fn.stdpath("config")

	-- 1. Fetch the latest info from origin in the background
	vim.fn.jobstart({"git", "-C", config_path, "fetch"}, {
		on_exit = function(_, exit_code)
			if exit_code ~= 0 then return end -- Quit if no internet or git error

			-- 2. Once fetch is done, check if we are behind the remote
			local status = vim.fn.system({"git", "-C", config_path, "status", "-sb"})

			if string.find(status, "behind") then
				vim.notify("(v) Config update available! Run :GitPullConfig", vim.log.levels.WARN, {
					title = "Neovim Config",
					icon = "(v)",
				})
			end
		end,
	})
end

-- Run the check on startup
vim.api.nvim_create_autocmd("VimEnter", { callback = check_config_updates })

-- 3. Create a command so you can pull manually when you're ready
vim.api.nvim_create_user_command("GitPullConfig", function()
	local config_path = vim.fn.stdpath("config")
	print("Updating config...")
	vim.fn.system({"git", "-C", config_path, "pull"})
	vim.notify("Config updated! Restart Neovim to apply.", vim.log.levels.WARN)
end, {})

